FROM debian

RUN : \
  && apt-get update \
  && apt-get install -y \
       wget \
       meson \
       pkg-config \
       libffi-dev \
       libexpat1-dev \
  && rm -rf /var/lib/apt/lists/* \
  ;

RUN : \
  && wget "https://wayland.freedesktop.org/releases/wayland-1.18.0.tar.xz" \
  && tar -xf wayland-* \
  && rm wayland-*.tar.xz \
  ;

RUN : \
  && cd wayland-* \
  && meson setup build \
       -Ddocumentation=false \
       -Ddtd_validation=false \
  && meson install -C build \
  ;
