[libraries]
kotlin-gradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22"

jetbrains-compose-runtime = "org.jetbrains.compose.runtime:runtime:1.6.0-rc03"
jetbrains-compose-compiler = "org.jetbrains.compose.compiler:compiler:1.5.8.1"
