[libraries]
kotlin-gradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.23"

jetbrains-compose-runtime = "org.jetbrains.compose.runtime:runtime:1.6.0"
jetbrains-compose-compiler = "org.jetbrains.compose.compiler:compiler:1.5.10"
