{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-metadata-0.0.0-SNAPSHOT.jar",
          "url": "lifecycle-runtime-compose-0.0.0-SNAPSHOT.jar",
          "size": 752,
          "sha512": "68322cbb83c1919df54e61376defe329771ceb865341c1e1c801a6d6a868d7ba8890b192cf03888a752a1558b1a4a8b9521bda1e1bfbf272a813ae9daf29f87c",
          "sha256": "3ac89306362ef058d587e25eac85fcddb9531987763758ec8a927ffeb902c966",
          "sha1": "236d61db873b97d81226e403c006f5bb44299aa4",
          "md5": "c4051909004e8a2b4efa027e4f3c733b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-kotlin-0.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-runtime-compose-0.0.0-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-linuxarm64/0.0.0-SNAPSHOT/lifecycle-runtime-compose-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-linuxarm64/0.0.0-SNAPSHOT/lifecycle-runtime-compose-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    }
  ]
}