{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.ui",
    "module": "ui-graphics",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-metadata-0.0.0-SNAPSHOT.jar",
          "url": "ui-graphics-0.0.0-SNAPSHOT.jar",
          "size": 762,
          "sha512": "48fea1b25e67e4053102d9cfb19e95253217eaddd1dcfe936111eed0c4986197e8734491f2a079fbc78c333f7e8cd55f8e6c18723abf6e8cdd6ea0b4e58bb813",
          "sha256": "341e72a847de5aed5ab474906c68d101b3e3e2a6d338ff8894c84eac88b18217",
          "sha1": "6ec08334d35aa024ec3d483bc11fff82a3c5dc88",
          "md5": "495294f5a6a6e1ba6eae0cb1eb765612"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ui-graphics-kotlin-0.0.0-SNAPSHOT-sources.jar",
          "url": "ui-graphics-0.0.0-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-linuxarm64/0.0.0-SNAPSHOT/ui-graphics-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-linuxarm64/0.0.0-SNAPSHOT/ui-graphics-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    }
  ]
}