{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.material",
    "module": "material-ripple",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-metadata-0.0.0-SNAPSHOT.jar",
          "url": "material-ripple-0.0.0-SNAPSHOT.jar",
          "size": 742,
          "sha512": "77966eec5c1cb83077094d71668546984ed6fcfd655c392047ad11e127100ff94b3b1c7cd670a8335a0510005749b536cf9feea0ec160788151f3bce0655cd36",
          "sha256": "46d87f34d0e14876d34befd77e6b6e8db44b527824ae933e6bec7bf8b403f2df",
          "sha1": "4ff26841f5542c1020ef65410f5c352af0ab19ab",
          "md5": "09af84ca7f6fd1b31c5259e4b3dc4337"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-ripple-kotlin-0.0.0-SNAPSHOT-sources.jar",
          "url": "material-ripple-0.0.0-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-ripple-linuxarm64/0.0.0-SNAPSHOT/material-ripple-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-ripple-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-ripple-linuxarm64/0.0.0-SNAPSHOT/material-ripple-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-ripple-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    }
  ]
}