{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-runtime-compose/0.0.0-SNAPSHOT/lifecycle-runtime-compose-0.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose.klib",
          "url": "lifecycle-runtime-compose-linuxarm64-0.0.0-SNAPSHOT.klib",
          "size": 35758,
          "sha512": "1e813b14ea6de7de058287f036e39c77465af94d9157aad174a5aee7121308c02adf6432d323409100c1414b9e5fb2e1caef399f6af35964ce77ce4eefcb0761",
          "sha256": "6e1d0804794c34bd8c1df07d01df7ed01b19c467fdbacb3ef75c9822e96bf66f",
          "sha1": "38ed84041b2a18f57d699beb4a5d7528a6dd6ff0",
          "md5": "a649cbacf918ac8c803936dd20815843"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-linuxarm64-0.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-runtime-compose-linuxarm64-0.0.0-SNAPSHOT-sources.jar",
          "size": 9079,
          "sha512": "134c886f3e77b5eaf26be03eb9fa8248c489b81e90f146fc2b636d98a0231b3dc78c391f9f80b50ee40a89f503976297fb3a9a44124b4530edbaadaa8555d91e",
          "sha256": "e061b0fd02662daf702ea143348a36044c03de01a45ef274899bfca0701c70f9",
          "sha1": "0011e1218dc376a70cab3447e1b38f680f31ecdd",
          "md5": "c187ca291e9de66b38adaf8a67fcbead"
        }
      ]
    }
  ]
}