{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.material",
    "module": "material-icons-core",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-metadata-0.0.0-SNAPSHOT.jar",
          "url": "material-icons-core-0.0.0-SNAPSHOT.jar",
          "size": 725,
          "sha512": "b1506ed7d533467486e6662fb8c00f511d4ca3248ed312125a918ef7c0c199087ef047cab411d35874bdd5cfc1029f55924420b38efb3689ea70ce1da6b60e43",
          "sha256": "1ec8cada4b9ab1141774505321390b326ea2ae9ef0b1d5d6546408e855c77f09",
          "sha1": "9c895d989eccc9b59282bf9597bf9c26d0283ec7",
          "md5": "aa03ab186e442f3bfcb35cbc03a3312b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-icons-core-kotlin-0.0.0-SNAPSHOT-sources.jar",
          "url": "material-icons-core-0.0.0-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-linuxarm64/0.0.0-SNAPSHOT/material-icons-core-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-linuxarm64/0.0.0-SNAPSHOT/material-icons-core-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    }
  ]
}