{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-0.0.0-SNAPSHOT.jar",
          "url": "foundation-0.0.0-SNAPSHOT.jar",
          "size": 778,
          "sha512": "146934cb136ddeac67831e5325a582517c1828e47dce792e75dee18e67a24e8fe127b0ecff96bbed47a75838d3daa03663a4611286be35e4a638afc7f44b8ae2",
          "sha256": "fd9a38bf52d96a863ab58946a5376bce4fb32819cd23031205d4d049e1aa2fc8",
          "sha1": "bf8fb8cf280353eb12f53f063a86fa0f0f1d9c49",
          "md5": "385d4e6e9c5b3a1d85a50a2e0db92e16"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "foundation-kotlin-0.0.0-SNAPSHOT-sources.jar",
          "url": "foundation-0.0.0-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-linuxarm64/0.0.0-SNAPSHOT/foundation-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.foundation",
        "module": "foundation-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-linuxarm64/0.0.0-SNAPSHOT/foundation-linuxarm64-0.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.foundation",
        "module": "foundation-linuxarm64",
        "version": "0.0.0-SNAPSHOT"
      }
    }
  ]
}