{
  "formatVersion": "1.1",
  "component": {
    "url": "../../skiko/0.0.0-SNAPSHOT/skiko-0.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "skiko.klib",
          "url": "skiko-linuxarm64-0.0.0-SNAPSHOT.klib",
          "size": 27466808,
          "sha512": "4d0d78c4a9892ca0373c15a48740388547a310a1cb488919f18725ff0d415d71f8cc176742ad0a7f963abe4410c79e39c2fd2cc933045fd30f92818c8ac5aa01",
          "sha256": "9710498ef5443f1f7056dd04c2649f33bbb7ad3ce800badfe89ae45673b3140d",
          "sha1": "99915e811e59caccc4adfd7571f575362f817211",
          "md5": "3d76d7c936aeb1d6c6552c0f14d3042c"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "skiko-linuxarm64-0.0.0-SNAPSHOT-sources.jar",
          "url": "skiko-linuxarm64-0.0.0-SNAPSHOT-sources.jar",
          "size": 245817,
          "sha512": "1149baa6173fb3f54e262f38de49e7d972428f1c3f48c6327eefed1f8de12914f9ef737f73a4ac1be201f82ec29fa96c8b0eec8131bf2b5a423639d58f062dd8",
          "sha256": "66e17fd8f8096cbd2513a95c7b56f5d35b0f993a704da7dcba8d21949e18804a",
          "sha1": "635adcb7a44764442a55328e7b8a7152bd970058",
          "md5": "751bb593764a00d80e32d868ca209f25"
        }
      ]
    }
  ]
}
