name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: composeui-lightswitch-debug.kexe
          path: build/bin/linuxArm64/debugExecutable/composeui-lightswitch.kexe
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: composeui-lightswitch-release.kexe
          path: build/bin/linuxArm64/releaseExecutable/composeui-lightswitch.kexe
          if-no-files-found: error
